# Neovim compatibility

# Neovim specific function treat
[[plugins]]
repo = 'lambdalisue/vim-quickrun-neovim-job'

[[plugins]]
repo = 'statiolake/vim-quickrun-runner-nvimterm'

[[plugins]]
repo = 'lambdalisue/pastefix.vim'

[[plugins]]
repo = 'kamykn/popup-menu.nvim'

[[plugins]]
repo = 'raghur/fruzzy'
# Denite/CtrlP related
hook_add = '''
  let g:fruzzy#usenative = 1
'''

# EOF
