# Neovim compatibility
## Remote Plugin support
# roxma/nvim-yarp and roxma/vim-hug-neovim-rpc need pynvim
# > pip install --upgrade pynvim
[[plugins]]
repo = 'roxma/nvim-yarp'
depends = ['vim-hug-neovim-rpc']
hook_post_update = '''
  " install pynvim for vim-hug-neovim-rpc
'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
hook_post_update = '''
  let g:dein#plugin.build = g:user.function.deno_build_python_package('pynvim')
'''

## checkhealth
[[plugins]]
repo = 'rhysd/vim-healthcheck'

# matchfuzzy only in vim
[[plugins]]
repo = 'mattn/ctrlp-matchfuzzy'
depends = ['ctrlp.vim']
# config in ctrlp.vim

# EOF
