# Neovim compatibility
## Remote Plugin support
# roxma/nvim-yarp and roxma/vim-hug-neovim-rpc need pynvim
# > pip install --upgrade pynvim
[[plugins]]
repo = 'roxma/nvim-yarp'
depends = ['vim-hug-neovim-rpc']
hook_post_update = '''
  " install pynvim for vim-hug-neovim-rpc
'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
hook_post_update = '''
  " pynvim is lib,do not use pipx
  if g:user.system.windows && g:user.function.executable('pip')
    let g:dein#plugin.build = 'pip install --upgrade pynvim'
  elseif g:user.function.executable('pip3')
    let g:dein#plugin.build = 'pip3 install --user --upgrade pynvim'
  endif
'''

## checkhealth
[[plugins]]
repo = 'rhysd/vim-healthcheck'

# matchfuzzy only in vim
[[plugins]]
repo = 'mattn/ctrlp-matchfuzzy'
depends = ['ctrlp.vim']
# config in ctrlp.vim

# EOF
