# vital lib : merged 0

[[plugins]]
repo = 'vim-jp/vital.vim'
# repo = 'tsuyoshicho/vital.vim'
# rev  = 'develop'
hook_post_source = '''
  " vital use
  let g:V = vital#vital#new()

  " vitalize need vital git repo
  " need merged=0
  " let g:vitalizer#vital_dir = ...
'''

[[plugins]]
repo = 'lambdalisue/vital-Whisky'
depends = ['vital.vim']

[[plugins]]
repo = 'lambdalisue/vital-ArgumentParser'
depends = ['vital.vim']

[[plugins]]
repo = 'lambdalisue/vital-Rx'
depends = ['vital.vim']

[[plugins]]
repo = 'lambdalisue/vital-Vim-Prompt'
depends = ['vital.vim']

[[plugins]]
repo = 'lambdalisue/vital-Vim-Lua-String'
depends = ['vital.vim']

[[plugins]]
repo = 'lambdalisue/vital-Data-Dict-Option'
depends = ['vital.vim']

[[plugins]]
repo = 'lambdalisue/vital-Data-String-Formatter'
depends = ['vital.vim']

[[plugins]]
repo = 'lambdalisue/vital-ProgressBar'
depends = ['vital.vim']

# lambdalisue obsolute lib
[[plugins]]
repo = 'lambdalisue/vital-Vim-Buffer-Anchor'
depends = ['vital.vim']

[[plugins]]
repo = 'LumaKernel/vital-Luv'
depends = ['vital.vim']

[[plugins]]
repo = 'hrsh7th/vim-vital-vs'
depends = ['vital.vim']

[[plugins]]
repo = 'tsuyoshicho/vital-codec'
# repo = 'D:\Data\ReposWork\git\vital-codec'
depends = ['vital.vim']

# EOF
